name: hg
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=0.12.0=py37h06a4308_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - asn1crypto=1.4.0=py_0
  - astor=0.8.1=py37h06a4308_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - catalogue=2.0.4=py37h89c1867_0
  - certifi=2021.10.8=py37h89c1867_1
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=4.0.0=py37h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=2.3.1=py37hc365091_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cupy=9.2.0=py37hfed0110_0
  - cymem=2.0.5=py37hcd2ae1e_2
  - cython-blis=0.7.4=py37h902c9e0_0
  - dbus=1.13.18=hb2f20db_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - expat=2.4.1=h2531618_2
  - fastrlock=0.6=py37hcd2ae1e_1
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-pasta=0.2.0=py_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2020.2=254
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.0=h27cfd23_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.1.0=h56837e0_2
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=py37h06a4308_0
  - markupsafe=2.0.1=py37h27cfd23_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - murmurhash=1.0.5=py37hcd2ae1e_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.2=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.4.0=py37h06a4308_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.0.2u=h516909a_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pathy=0.6.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.0.1=py37h06a4308_0
  - preshed=3.0.5=py37hcd2ae1e_1
  - prometheus_client=0.10.1=pyhd3eb1b0_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - protobuf=3.14.0=py37h2531618_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pydantic=1.8.2=py37h5e8e339_0
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.0=h6e4f718_3
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - qt=5.9.6=h8703b6f_2
  - qtconsole=5.0.3=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - regex=2021.4.4=py37h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - sacremoses=master=py_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37h06a4308_0
  - shellingham=1.4.0=pyh44b312d_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py37h06a4308_0
  - smart_open=5.1.0=pyhd8ed1ab_1
  - spacy=3.1.1=py37hda21425_0
  - spacy-legacy=3.0.8=pyhd8ed1ab_0
  - sqlite=3.33.0=h62c20be_0
  - srsly=2.4.1=py37hcd2ae1e_0
  - statsmodels=0.12.2=py37h902c9e0_0
  - tensorflow-base=2.0.0=mkl_py37h9204916_0
  - thinc=8.0.8=py37hda21425_0
  - tk=8.6.10=hbc83047_0
  - tokenizers=0.10.1=py37_0
  - torchaudio=0.7.0=py37
  - torchvision=0.8.1=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - transformers=4.4.2=py_0
  - typer=0.3.2=pyhd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - wasabi=0.8.2=pyh44b312d_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - astunparse==1.6.3
    - bert-score==0.3.9
    - bpemb==0.3.3
    - cachetools==4.2.1
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - dataclasses==0.6
    - datasets==1.6.0
    - decorator==4.4.2
    - deprecated==1.2.12
    - dill==0.3.3
    - docopt==0.6.2
    - editdistance==0.5.3
    - en-core-web-sm==3.1.0
    - entrypoints==0.3
    - flair==0.8
    - flatbuffers==1.12
    - fsspec==2021.4.0
    - ftfy==6.0.1
    - future==0.18.2
    - gast==0.4.0
    - gdown==3.12.2
    - gensim==3.8.3
    - google-auth==1.29.0
    - google-auth-oauthlib==0.4.4
    - gpytorch==1.4.1
    - grpcio==1.34.1
    - h5py==3.1.0
    - huggingface-hub==0.0.8
    - hyperopt==0.2.5
    - importlib-metadata==3.10.1
    - install==1.3.4
    - ipykernel==5.5.5
    - ipython==7.24.1
    - janome==0.4.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - jiwer==2.2.0
    - keras-nightly==2.5.0.dev2021032900
    - kiwisolver==1.3.1
    - konoha==4.6.4
    - langdetect==1.0.8
    - language-tool-python==2.5.3
    - lemminflect==0.2.2
    - lru-dict==1.1.7
    - lxml==4.6.3
    - matplotlib==3.4.1
    - matplotlib-inline==0.1.2
    - more-itertools==8.7.0
    - mpld3==0.3
    - multiprocess==0.70.11.1
    - networkx==2.5.1
    - nltk==3.6.2
    - num2words==0.5.10
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - overrides==3.1.0
    - pandas==1.1.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-levenshtein==0.12.2
    - pytz==2021.1
    - pyzmq==22.1.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.4.1
    - seaborn==0.11.1
    - segtok==1.5.10
    - sentence-transformers==1.2.0
    - sentencepiece==0.1.95
    - sklearn==0.0
    - smart-open==5.0.0
    - sqlitedict==1.7.0
    - tabulate==0.8.9
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - tensorflow-hub==0.12.0
    - tensorflow-text==2.5.0
    - termcolor==1.1.0
    - terminado==0.10.0
    - terminaltables==3.1.0
    - testpath==0.5.0
    - textattack==0.3.3
    - threadpoolctl==2.1.0
    - tqdm==4.49.0
    - typing-extensions==3.7.4.3
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - word2number==1.1
    - xxhash==2.0.2